### ISSUE TITLE
算法中capital未参与bulletproofs过程，可以证明收益但无法证明收益率

### ISSUE THREAD

**Issue by fakezkpnl** [0kPN1/zkp-ak#1]
这真的是一个很牛的创意和实现方式。在读代码的过程中，我做了这样的一个fake proof，还请AK和程序大神看一下是否算是一个漏洞
[proof.zip](https://github.com/0kPN1/zkp-ak/files/3681254/proof.zip)
[config.zip](https://github.com/0kPN1/zkp-ak/files/3681263/config.zip)

**Comment by fakezkpnl** [comment]
如何证明只用了config.toml里面指定的capital这么多本金？

**Comment by 0kPN1** [comment]
quote from ak

> 如果意思是短时间可以用超大仓位做超大收益 这个没关系 觉得哪个操作有问题 直接质疑 我可以公开对应操作的数量明文 这个本质上属于怀疑操作量和市场流动性不匹配 证明办法都是质疑哪个就公开哪个即可 不存在自动证明方式 因为操作量必须去取交易所的历史成交数据才能比对证实

> “用了”多少本金不重要 因为交易所大部分都带杠杆 重要的是亏损量不可以大于本金数量 任何时候只要亏损量大于本金数量了 log return就会变成负无穷 pnl曲线上一眼就能看出来 试图用大杠杆操作博取短期高收益 一定会产生亏光的风险 这是不可逆的 而且只要一次 就前功尽弃

**Comment by fakezkpnl** [comment]
每个一条的方式可能对AK造成了困扰，因为不希望公开身份，所以用了小号，导致所有的回复消息和私信AK都看不到。微博上我不再回复。
我是纯粹被技术吸引来做这个讨论的，如果还愿意交流，我会在这里继续，如果觉得是无理取闹，关闭这个Bug即可。

**Comment by 0kPN1** [comment]
本程序无法证明本金，但这并不是问题。AK已经在微博解释，我这里再补充说明几点。
1. 交易所通常支持杠杆，持仓价值超过本金本来就是允许的。
2. 只要交易所流动性支持，高杆杠博取短期高收益也本来就是可能的。
3. 你贴出的证明相当于高风险赌博只赌了一次，只要多做几次，一定破产，即亏损已经超过本金，无法继续。
那么论点就变成，做每一步操作时，持仓的亏损有无超过本金。
1. 从目前已经公开的证明以及由其作出的收益曲线可以看到最大亏损远小于我们事先申明的本金。
2. 由于目前给出的收益率只精确到1天单位，如果仍有怀疑，可以增加一个range proof来证明进行每一步操作时的已有亏损并没有超过本金。你可以看到每一步操作时的总pnl都做了commitment。
3. 如果仍觉得精度不够，可以提出任何怀疑的时间点，比如某个插针行情。我们可以取得针尖上的价格计算当时的盈亏，来证明我们并没有破产。

**Comment by 0kPN1** [comment]
另外，本金300万，本来就是一个假设。即我们通过本程序证明了，假如我们有300万本金，我们有能力做出这个收益率。

你在微博上提到，年化1%的套利策略，能否通过减少计算收益率的本金，做到年化100%。先不论像swap的利息，本程序并无法记录。我们就假设你说的是个年化1%交易策略，如果它的最大回撤允许你在大量减少本金的情况下用高杠杆开等量仓位而不爆仓，那当然就证明了你的策略可以做到年化100%。

**Comment by fakezkpnl** [comment]
对于“本程序无法证明本金，但这并不是问题”那个楼层的内容，我完全同意，这也不是我认为有问题的点。

我明白AK帖子里面说的在当前配置文件下，是无法做出低风险套利策略的。我的问题不针对AK和他的配置文件。

我的问题在认为该算法（或者AK说的“源码”）可以证明收益，但并没有做出“假如我们有300万本金，我们有能力做出这个**收益率**”这样的证明。收益率必然要牵涉本金否则没法叫做“率”，而在代码中capital并没有参与到bulletproofs的过程里面。为了证明这一点，也许可以在constrain里面加入交易持仓对保证金的占用和本金的关系。

**Comment by AK-AlbertTheKing** [comment]
https://www.weibo.com/5080547782/I9GQpjKtp
此条微博及其引用内容解释的很清楚了 建议好好看看 capital的具体数字与收益率无关 群友跟操作是按系数跟的 群友资产/300w刀=系数 群友开仓数量=我的开仓数量*系数 决定群友收益率的是我的开仓量/300w刀 而不是300w刀这个数字 能明白么？换言之我可以把开仓数量改成仓位比例（例如买入10%仓位这种） 实际效果是一模一样的 我的capital到底是多少 根本无所谓

**Comment by fakezkpnl** [comment]
AK，我并不是在质疑你，我是在向程序作者提个建议如何可以做的更好。不再回复

**Comment by AK-AlbertTheKing** [comment]
谢谢
