### ISSUE TITLE
目前哈希上链的过程没有证明除公布操作外没有做其他未公开操作

### ISSUE THREAD

**Issue by fakezkpnl** [0kPN1/zkp-ak#2]
通过在链上检索哈希可以证明在该时间点前确实发出了操作指令，但没有证明没有同时发出其他未公开指令。
微博可以证明这一点，但是由于是一个可删的中心化平台，除非有人一直用程序监控，否则无法证明微博公布的哈希没有删过。
对于恶意操纵的人可以做如下操作：
  备份当前data文件夹为data.bak
  开多
  多仓哈希上链/微博
  备份当前data文件夹为data.long
  恢复data.bak
  开空
  空仓哈希上链/微博
  备份当前data文件夹为data.short
  根据市场行情恢复备份的data文件夹，删除不利微博，生成proof
  重复该过程

建议在以太坊上做一个contract，只留追加和读取的接口，然后将contract地址放在transcript中。

**Comment by AK-AlbertTheKing** [comment]
这个我原文介绍的很清楚啊 本来系统就是这么运行的
originstamp每天只能上一次链 所以实时操作只能发在微博 微博是公开的 你发现任何删帖的证据截图便是 帖子里都有sig的 你也造不了假 你要是愿意 随便程序监控发操作的微博账号 24*7 没任何问题
只要有一次删帖记录 而且删掉的密文解密后发现是不利于收益的话 整个验证流程的信任度就降低了 这个是不可逆的 就好像只要某人公开撒谎一次 大家就会认为他是个骗子

**Comment by fakezkpnl** [comment]
AK，我并不是在质疑你，我是在向程序作者提个建议如何可以做的更好。不再回复
